In [91]:
mylist=[1,2,3]

In [92]:
import numpy as np

In [93]:
arr=np.array(mylist)

In [94]:
arr

array([1, 2, 3])

In [95]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [96]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [98]:
np.zeros(3)

array([0., 0., 0.])

In [99]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [100]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [101]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [102]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [103]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
np.random.rand(4)

array([0.35806598, 0.29694648, 0.28769551, 0.63764361])

In [105]:
np.random.randn(2)

array([ 1.88372798, -1.58792413])

In [106]:
np.random.randint(1,100)

66

In [107]:
arr = np.arange(25)

In [108]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [109]:
ranarr = np.random.randint(0,50,10)

In [110]:
ranarr

array([ 4, 11, 35, 23, 27, 12, 26,  1, 10, 13])

In [111]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
ranarr.max()

35

In [113]:
ranarr.min()

1

In [114]:
ranarr.argmax()
ranarr.argmin()

7

In [115]:
arr = arr.reshape(5,5)

In [116]:
arr.shape

(5, 5)

In [117]:
arr.dtype

dtype('int32')

In [118]:
arr = np.arange(0,11)

In [119]:
arr[8]

8

In [120]:
arr[1:5]

array([1, 2, 3, 4])

In [121]:
arr[:5]

array([0, 1, 2, 3, 4])

In [122]:
arr[:5] = 100

In [123]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [124]:
arr = np.arange(0,11)

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
slice_of_arr = arr[:6] #doesnt copy array

In [127]:
slice_of_arr[:] = 99

In [128]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [129]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [130]:
arr_copy = arr.copy() # will get copy of array rather than link to original array

In [131]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [132]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [133]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [134]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [135]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [136]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [137]:
arr_2d[1,2] #can use one bracket with comma or 2 separate brackets

30

In [138]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [139]:
arr > 5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [140]:
arr = np.arange(0,11)

In [141]:
bool_arr = arr > 5

In [142]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [143]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [144]:
arr_2d = np.arange(50).reshape(5,10)

In [145]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [146]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

NumPy Operations

In [147]:
import numpy as np

In [148]:
arr = np.arange(0,11)

In [149]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [151]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [152]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [153]:
arr/ arr

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [154]:
 arr ** 2


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [155]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [156]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [157]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [158]:
np.log(arr)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])